# -*- coding: utf-8 -*-
"""Python_Clase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvpjpjKpsHJNGo_zPlZv3_IMhYD4O_HY
"""

print("La Witsi Witsi\nsubio a su telaraña.")
print()
print("Vino la lluvia\ny se la llevò.")
print()
print("Mi nombre es", "Python.", end=" ") # end=" " elimina el ultimo salto de line y agrega el simbolo especial en este caso un espacio
print("Monty Python.")
print()
print("Mi", "nombre", "es", "Monty", "Python.", sep="-") # sep="-" separa cada palabra con el caracter que le colocamos a sep=
print()
print("Mi\nnombre\nes\nBond.", end=" ")
print("James Bond.")
print()
print("fish", "chips", sep="&")
print()
print('Greg\'s book.')

print("'Greg's book.'")

print('"Greg\'s book."')

print("Greg\'s book.")

print('"Greg\'s book."') # La comil, la simple ' sin la \ da error \' es una funcion para indicar que la comilla es un caracter

print(2 ** 3) # Cuando ambos argumentos son enteros el resultado es entero
print(2 ** 3.) # Cuando un argumento es entero y otro es flotante el resultado es flotante
print(2. ** 3)
print(2. ** 3.) # son potencias con **
print()
print(2 * 3)
print(2 * 3.)
print(2. * 3)
print(2. * 3.)
print()
print(6 / 3)
print(6 / 3.)
print(6. / 3)
print(6. / 3.)
print()
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)
print()
print((2 ** 4), (2 * 4.), (2 * 4))
print((-2 / 4), (2 / 4), (2 // 4), (-2 // 4)) # El -2//4 se redondea hacia abajo
print((2 % -4), (2 % 4), (2 ** 3 ** 2)) # la potencia se resuelve de derecha a izquierda seria 3 a la 2 y luego 2 a la 9

var = "3.8.5"
print("Python version: " + var)

print("Dime lo que sea...")
print()
anything = input("Dime lo que sea...") # la funcion imput permite ingresar datos que guarda el programa en una variable para su uso posterior
print("Hmm...", anything, "...¿en serio?")

anything = float(input("Ingresa un número: "))
something = anything ** 2.0
print(anything, "a la potencia de 2 es", something)

fnam = input("¿Me puedes dar tu nombre por favor? ")
lnam = input("¿Me puedes dar tu apellido por favor? ")
print("Gracias")
print("\nTu nombre es " + fnam + " " + lnam + ".")

print("+", "-" * 11, "+")
print("|             |\n" * 5, end="")
print("+", "-" * 11, "+")